spring.application.name=Bus Management System
spring.datasource.url=jdbc:postgresql://localhost:5432/BusManagementDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Suppress static resource warnings
spring.web.resources.add-mappings=false

# Hibernate settings (optional but common)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


#OAuth2 Configuration(Google)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#OAuth2 Configuration(Github)
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email  
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github

# Suppress open-in-view warning
spring.jpa.open-in-view=false

# Suppress favicon warning
spring.mvc.favicon.enabled=false